### ISSUE TITLE
Running pnpm turbo cannot find module 'contentlayer/generated'

### ISSUE THREAD

**Issue by 5amfung** [shadcn/taxonomy#129]
Anyone has luck using the Turbopack by running `pnpm turbo`?

I get the following error.

```
error - Error: Cannot find module 'contentlayer/generated'
    [at /Users/sfung/src/doughy/.next/server/app/chunks/ssr/app_b74d6a._.js:298:15]
    [at /Users/sfung/src/doughy/.next/server/app/chunks/ssr/app_b74d6a._.js:301:3]
    [at [project]/app/(marketing)/blog/page.tsx (ecmascript, rsc) (/Users/sfung/src/doughy/.next/server/app/chunks/ssr/app_b74d6a._.js:442:3)]
    [at /Users/sfung/src/doughy/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_05a537._.js:412:21]
    [at runModuleExecutionHooks (/Users/sfung/src/doughy/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_05a537._.js:456:3)]
    [at instantiateModule (/Users/sfung/src/doughy/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_05a537._.js:410:3)]
    [at getOrInstantiateModuleFromParent (/Users/sfung/src/doughy/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_05a537._.js:498:10)]
    [at esmImport (/Users/sfung/src/doughy/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_05a537._.js:181:18)]
    [at Module.default (/Users/sfung/src/doughy/.next/server/app/chunks/ssr/app_b74d6a._.js:446:20)]
    at Array.<anonymous> (/turbopack/[next]/entry/app-renderer.tsx:18:12) [/Users/sfung/src/doughy/.next/server/app/chunks/ssr/[next]_entry_app-renderer.tsx_e75b2a._.js:62:174]
    at getLayoutOrPageModule (node_modules/.pnpm/next@13.3.1_@babel+core@7.21.4_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/app-dir-module.js:22:30) [/Users/sfung/src/doughy/.next/server/app/chunks/ssr/node_modules_.pnpm_70e926._.js:6502:30]
    18 |     if (isLayout) {
    19 |         value = await layout[0]();
    20 |         modType = "layout";
    21 |     } else if (isPage) {
       +                              v
    22 +         value = await page[0]();
       +                              ^
    23 |         modType = "page";
    24 |     } else if (isDefaultPage) {
    25 |         value = await defaultPage[0]();
    26 |         modType = "page";

```

**Comment by shadcn** [comment]
This is known issue with Contentlayer. 

You need to modify your script for `turbo`. See examples:

```json
    "dev": "concurrently \"contentlayer dev\" \"next dev\"",
    "build": "contentlayer build && next build"
```

**Comment by tylergalpin** [comment]
See my suggestion here: #122

**Comment by deCaldas** [comment]
@shadcn, it may work better...

> `"build": "next build"`
