### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by leonardodincalci** [shadcn/taxonomy#139]
Hello, after pnpm dev I receive these errors:

```
[1] ready - started server on 0.0.0.0:3000, url: http://localhost:3000
[1] info  - Loaded env from /Users/imac24service/Desktop/taxonomy-main/.env.local
[0] Contentlayer config change detected. Updating type definitions and data...
[0] Generated 15 documents in .contentlayer
[1] ❌ Invalid environment variables: {
[1]   SMTP_FROM: [ 'String must contain at least 1 character(s)' ],
[1]   POSTMARK_API_TOKEN: [ 'String must contain at least 1 character(s)' ],
[1]   POSTMARK_SIGN_IN_TEMPLATE: [ 'String must contain at least 1 character(s)' ],
[1]   POSTMARK_ACTIVATION_TEMPLATE: [ 'String must contain at least 1 character(s)' ],
[1]   STRIPE_API_KEY: [ 'String must contain at least 1 character(s)' ],
[1]   STRIPE_WEBHOOK_SECRET: [ 'String must contain at least 1 character(s)' ],
[1]   STRIPE_PRO_MONTHLY_PLAN_ID: [ 'String must contain at least 1 character(s)' ]
[1] }
[1] error - Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
[1] Error: Invalid environment variables
[1]     at f (file:///Users/imac24service/Desktop/taxonomy-main/node_modules/.pnpm/@t3-oss+env-nextjs@0.2.2_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:505)
[1]     at l (file:///Users/imac24service/Desktop/taxonomy-main/node_modules/.pnpm/@t3-oss+env-nextjs@0.2.2_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:695)
[1]     at C (file:///Users/imac24service/Desktop/taxonomy-main/node_modules/.pnpm/@t3-oss+env-nextjs@0.2.2_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:868)
[1]     at file:///Users/imac24service/Desktop/taxonomy-main/env.mjs:4:20
[1]     at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
[1]   type: 'Error'
[1] }
[1] next dev exited with code 1

```

**Comment by leonardodincalci** [comment]
I solved. I rename the .env.local to .env and edit the line with a blank space 

...

# -----------------------------------------------------------------------------
# Email (Postmark)
# -----------------------------------------------------------------------------
SMTP_FROM=" "
POSTMARK_API_TOKEN=" "
POSTMARK_SIGN_IN_TEMPLATE=" "
POSTMARK_ACTIVATION_TEMPLATE=" "

# -----------------------------------------------------------------------------
# Subscriptions (Stripe)
# -----------------------------------------------------------------------------
STRIPE_API_KEY=" "
STRIPE_WEBHOOK_SECRET=" "
STRIPE_PRO_MONTHLY_PLAN_ID=" "

--
