### ISSUE TITLE
pnpm dev with error

### ISSUE THREAD

**Issue by alaneuler** [shadcn/taxonomy#168]
Newly cloned projects (main branch), run with `pnpm install`, `cp .env.example .env.local` (changed nothing) and `pnpm build`, last command failed with error:

```
> taxonomy@0.2.0 build /home/alaneuler/projects/taxonomy
> contentlayer build && next build

Generated 15 documents in .contentlayer
uncaughtException /home/alaneuler/projects/taxonomy/node_modules/.pnpm/next@13.3.2-canary.13_@babel+core@7.21.4_@opentelemetry+api@1.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1190
        additionalSsgPathsByPath[pathsPage] ||= {};
                                            ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/alaneuler/projects/taxonomy/node_modules/.pnpm/next@13.3.2-canary.13_@babel+core@7.21.4_@opentelemetry+api@1.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/entries.js:59:16)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
 ELIFECYCLE  Command failed with exit code 1.
```

Have tries `pnpm dev`, same error here.

Other info:
```
> uname -a
Linux playground.local 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux

> pnpm -v
8.6.1
```

**Comment by alaneuler** [comment]
Found the problem, I'm using node with v14.21.3, upgrading it to v18.16.0 eliminates the problem.
