### ISSUE TITLE
undefined og.jpeg

### ISSUE THREAD

**Issue by theapplegates** [shadcn/taxonomy#41]
I get this error when I try and build the site.
```
Nov 28 10:08:42 AM  TypeError [ERR_INVALID_URL]: Invalid URL
Nov 28 10:08:42 AM      at new NodeError (node:internal/errors:387:5)
Nov 28 10:08:42 AM      at URL.onParseError (node:internal/url:565:9)
Nov 28 10:08:42 AM      at new URL (node:internal/url:641:5)
Nov 28 10:08:42 AM      at MdxHead (/opt/render/project/src/.next/server/chunks/6564.js:26:17)
Nov 28 10:08:42 AM      at T (/opt/render/project/src/.next/server/chunks/5245.js:20716:25)
Nov 28 10:08:42 AM      at Ma (/opt/render/project/src/.next/server/chunks/5245.js:20879:33)
Nov 28 10:08:42 AM      at Object.toJSON (/opt/render/project/src/.next/server/chunks/5245.js:20672:32)
Nov 28 10:08:42 AM      at stringify (<anonymous>)
Nov 28 10:08:42 AM      at V (/opt/render/project/src/.next/server/chunks/5245.js:20971:53)
Nov 28 10:08:42 AM      at AsyncLocalStorage.run (node:async_hooks:330:14) {
Nov 28 10:08:42 AM    input: 'undefined/og.jpg',
Nov 28 10:08:42 AM    code: 'ERR_INVALID_URL'

```

I think it is looking for "undefined/og.jpg" instead of the valid `og.jpg`

Not sure if I am right since I am not a developer.

Thanks
Paul

**Comment by shadcn** [comment]
Did you add the required environment variables? Can you confirm if you have `NEXT_PUBLIC_APP_URL`?

**Comment by theapplegates** [comment]
I do not have that. I must have missed that. These are the .env values I have. Sorry for the PDF. I'm in a car. 
[Project Settings – Dashboard – Vercel.pdf.pdf](https://github.com/shadcn/taxonomy/files/10105902/Project.Settings.Dashboard.Vercel.pdf.pdf)

**Comment by theapplegates** [comment]
My bad I do have that already.

**Comment by theapplegates** [comment]
I deleted it and added it bad. Things work now. Thanks for the quick help. Enjoy your day.
